# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _                 
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                 /____/        
#
# Title of your website
title: "Friends of the Dales - Become a Member"

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Become a member of the Friends of the Dales and you'll receive a fantastic magazine four times a year plus free entry to our annual events programme. Friends of the Dales is a registered charity set up in 1981 to campaign for the protection and enhancement of the Dales and to encourage everyone to value and enjoy this special area."

# This URL is the main address. Don't include a slash at the end.
#
url: "https://freindsofthedales.github.io"
admin_email: "fotd@bjorsq.net"
urlimg: "https://freindsofthedales.github.io/assets/img/"

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
excerpt_separator: "\n\n"

# The language setting is used in /includes/header.html for html-settings
language: "en"

# Include/exclude files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

#
#       ____       ____            ____ 
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_  
#   /_____/\___/_/  \__,_/\__,_/_/\__/  
#                                       
# Default Settings

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: true 	# Show metadata beneath all pages
      comments: false
      author: "Peter Edwards"
      layout: page
  -
    scope:
      path: ""        
      type: "posts"
    values:
      show_meta: true   # Show metadata beneath all posts
      comments: false
      author: "Peter Edwards"

#       ______            _                      
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  ) 
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicons, Apple Touch Buttons
#                                                 More information » http://j.mp/apple-touch-icons

favicon:          "/assets/img/icons/favicon.ico"
favicon16:        "/assets/img/icons/favicon-16x16.png"
favicon32:        "/assets/img/icons/favicon-32x32.png"
faviconmanifest:  "/assets/img/icons/site.webmanifest"
apple_touch_icon: "/assets/img/icons/apple-touch-icon.png"

msapplication_tilecolor:         "#ffffff"                                        # Windows 8 Tile Backgroundcolor

#      _____                
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/ 
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#                           

sass:
    sass_dir: _scss
    style: compact


#     _____           _       __      
#    / ___/__________(_)___  / /______
#    \__ \/ ___/ ___/ / __ \/ __/ ___/
#   ___/ / /__/ /  / / /_/ / /_(__  ) 
#  /____/\___/_/  /_/ .___/\__/____/  
#                  /_/                
#

